const categorySectionMap = {
    en: {

        "Photography": [
            "Account",
            "Adobe Content Authenticity",
            "Adobe Events",
            "Adobe Express",
            "Adobe Express Developers",
            "Adobe Firefly",
            "Bridge",
            "Camera Raw",
            "Color Management",
            "Creative Cloud Services",
            "Download & Install",
            "Lightroom Classic",
            "Lightroom ecosystem (Cloud-based)",
            "Photoshop (Beta)",
            "Photoshop Camera (read-only)",
            "Photoshop Elements",
            "Photoshop Express",
            "Photoshop ecosystem",
            "Spark Page and Video on iOS",
            "Stock",
            "Stock Contributors"
        ],
        "Design & Layout": [
            "Account, Payment, & Plan",
            "Acrobat",
            "Acrobat Reader",
            "Adobe Capture",
            "Adobe Color",
            "Adobe Content Authenticity",
            "Adobe Events",
            "Adobe Express",
            "Adobe Express Developers",
            "Adobe Firefly",
            "Adobe Fonts",
            "Adobe Substance 3D Viewer (Beta)",
            "Adobe XD",
            "Bridge",
            "Color Management",
            "Creative Cloud Services",
            "Dimension",
            "Download & Install",
            "Dreamweaver",
            "Fireworks",
            "Illustrator",
            "Illustrator on the iPad",
            "InCopy",
            "InDesign",
            "Photoshop (Beta)",
            "Photoshop ecosystem",
            "Spark Page and Video on iOS",
            "Stock"
        ],
        "Video & Motion": [
            "Account, Payment, & Plan",
            "Adobe Capture",
            "Adobe Events",
            "Adobe Express",
            "Adobe Express Developers",
            "Adobe Firefly",
            "Adobe Fonts",
            "Adobe Media Encoder",
            "Adobe Media Encoder (Beta)",
            "Adobe Podcast",
            "After Effects",
            "After Effects (Beta)",
            "Animate",
            "Audition",
            "Audition (Beta)",
            "Bridge",
            "Character Animator",
            "Character Animator (Beta)",
            "Color Management",
            "Creative Cloud Services",
            "Download & Install",
            "Flash Player (read-only)",
            "Media Server (read-only)",
            "Photoshop (Beta)",
            "Photoshop ecosystem",
            "Premiere Elements",
            "Premiere Pro",
            "Premiere Pro (Beta)",
            "Premiere Rush",
            "Premiere on Iphone",
            "Spark Page and Video on iOS",
            "Stock",
            "Stock Contributors",
            "Team Projects",
            "Video Hardware",
            "Video Lounge"
        ],
        "Illustration": [
            "Account, Payment, & Plan",
            "Adobe Capture",
            "Adobe Content Authenticity",
            "Adobe Events",
            "Adobe Firefly",
            "Color Management",
            "Creative Cloud Services",
            "Download & Install",
            "Fresco",
            "Illustrator",
            "Illustrator (Beta)",
            "Illustrator on the iPad",
            "Photoshop (Beta)",
            "Photoshop ecosystem",
            "Project Neo (beta)",
            "Spark Page and Video on iOS",
            "Stock Contributors"
        ],
        "UI and UX": [
            "Account, Payment, & Plan",
            "Adobe Capture",
            "Adobe Events",
            "Adobe Firefly",
            "Adobe Fonts",
            "Adobe XD",
            "After Effects",
            "Animate",
            "ColdFusion",
            "Creative Cloud Services",
            "Download & Install",
            "Dreamweaver",
            "Illustrator",
            "Illustrator on the iPad",
            "Photoshop (Beta)",
            "Photoshop ecosystem"
        ],
        "Documents & PDF": [
            "Account, Payment, & Plan",
            "Acrobat",
            "Acrobat Reader",
            "Acrobat Reader Mobile",
            "Acrobat SDK",
            "Acrobat Services API",
            "Adobe Acrobat Online",
            "Adobe Acrobat Sign",
            "Adobe Fonts",
            "Adobe Scan",
            "Color Management",
            "Creative Cloud Services",
            "Download & Install",
            "InDesign",
            "PostScript",
            "Stock",
            "Type & Typography"
        ],
        "Business Solutions": [
            "Acrobat",
            "Adobe Learning Manager",
            "Air",
            "Business Catalyst (read-only)",
            "Captivate",
            "ColdFusion",
            "Connect",
            "Digital Editions",
            "Enterprise & Teams",
            "Experience Cloud Community",
            "Flash Player (read-only)",
            "FrameMaker",
            "RoboHelp",
            "Spark Page and Video on iOS",
            "Team Projects"
        ],
        "Community": [
            "Abuse Reports",
            "Adobe Events",
            "Back Room",
            "Content Filter Notifications",
            "Exchange",
            "Holding Room",
            "Photoshop Developers",
            "Stock Contributors",
            "The Lounge",
            "User Group Managers",
            "Using the Community"
        ],
        "Technical Communication and eLearning": [
            "Adobe Learning Manager",
            "Captivate",
            "FrameMaker",
            "RoboHelp"
        ],
        "3D & AR": [
            "Adobe Aero",
            "Adobe Firefly",
            "Adobe Substance 3D Viewer (Beta)",
            "Dimension",
            "Mixamo",
            "Project Neo (beta)",
            "Substance 3D Assets and Community Assets",
            "Substance 3D Designer",
            "Substance 3D Modeler",
            "Substance 3D Painter",
            "Substance 3D Plugins",
            "Substance 3D Sampler",
            "Substance 3D Stager"
        ]
    },
    ja: {
        "一般": [
            "Adobe MAX 2025/ The Japan Lounge",
            "Creative Cloudのダウンロードとインストール",
            "Creative Cloudサービス",
            "JP Abuse Reports",
            "Japan Back Room",
            "アカウント / 支払い / プラン",
            "アドビサポートコミュニティ 総合案内",
            "永続版ライセンス製品"
        ],
        "写真": [
            "Adobe Express フォーラム",
            "Camera Rawフォーラム",
            "Lightroom Classicフォーラム",
            "Lightroomフォーラム",
            "Photoshop (Beta) フォーラム",
            "Photoshop Cameraフォーラム",
            "Photoshop Elementsフォーラム",
            "Photoshop Expressフォーラム",
            "Photoshop Fixフォーラム",
            "Photoshop Mixフォーラム",
            "Photoshop Sketchフォーラム",
            "Photoshop デスクトップ/Mobile/web 版",
            "Stockフォーラム"
        ],
        "グラフィックデザイン": [
            "Adobe Captureフォーラム",
            "Adobe Colorフォーラム",
            "Adobe Compフォーラム",
            "Adobe Express フォーラム",
            "Adobe Fontsフォーラム",
            "Bridgeフォーラム",
            "Fireworksフォーラム",
            "Illustrator on the web (ベータ)",
            "InCopyフォーラム",
            "InDesignフォーラム",
            "Photoshop (Beta) フォーラム",
            "Photoshop デスクトップ/Mobile/web 版",
            "Spark Page and Video on iOS"
        ],
        "ビデオ": [
            "Adobe Express フォーラム",
            "After Effectsフォーラム",
            "Animateフォーラム",
            "Auditionフォーラム",
            "Character Animatorフォーラム",
            "Flash Playerフォーラム",
            "Flex / Flash Builderフォーラム",
            "Media Encoderフォーラム",
            "Photoshop (Beta) フォーラム",
            "Photoshop デスクトップ/Mobile/web 版",
            "Preludeフォーラム",
            "Premiere Elementsフォーラム",
            "Premiere Proフォーラム",
            "Premiere Rushフォーラム",
            "Video Hardwareフォーラム"
        ],
        "イラストレーション": [
            "Frescoフォーラム",
            "Illustrator Drawフォーラム",
            "Illustrator on the web (ベータ)",
            "Illustratorフォーラム",
            "Photoshop (Beta) フォーラム",
            "Photoshop デスクトップ/Mobile/web 版"
        ],
        "UIとUX": [
            "Adobe XDフォーラム",
            "Dreamweaverフォーラム",
            "Illustrator on the web (ベータ)",
            "Museフォーラム",
            "Photoshop (Beta) フォーラム",
            "Photoshop デスクトップ/Mobile/web 版"
        ],
        "AcrobatとPDF": [
            "Acrobat Reader / Acrobat DC for Mobileフォーラム",
            "Acrobatフォーラム",
            "Adobe Acrobat Sign / Document Cloudフォーラム",
            "Adobe Scanフォーラム"
        ],
        "ビジネスソリューション": [
            "Adobe AIRフォーラム",
            "Captivate / Captivate Primeフォーラム",
            "Contributeフォーラム",
            "Creative Cloud 法人エンタープライズ版",
            "Creative Cloud 法人グループ版",
            "Digital Editionsフォーラム",
            "FrameMakerフォーラム",
            "RoboHelpフォーラム"
        ],
        "3D＆AR": [
            "Dimensionフォーラム"
        ]
    },
    ko: {
        "사진": [
            "Adobe Express",
            "Bridge 게시판",
            "Camera Raw 게시판",
            "Creative Cloud 게시판",
            "Lightroom Classic 게시판",
            "Lightroom 게시판",
            "Photoshop Camera 게시판",
            "Photoshop Express 게시판",
            "Photoshop 게시판",
            "Stock Contributor 게시판",
            "Stock 게시판",
            "계정, 결제 및 플랜",
            "다운로드 및 설치 게시판"
        ],
        "그래픽 디자인": [
            "Acrobat Reader 게시판",
            "Acrobat 게시판",
            "Adobe Express",
            "Adobe Fonts 게시판",
            "Adobe XD 게시판",
            "Bridge 게시판",
            "Creative Cloud 게시판",
            "Dimension 게시판",
            "Illustrator 게시판",
            "InDesign 게시판",
            "Photoshop 게시판",
            "Stock 게시판",
            "계정, 결제 및 플랜",
            "다운로드 및 설치 게시판"
        ],
        "비디오": [
            "Adobe Express",
            "Adobe Fonts 게시판",
            "After Effects 게시판",
            "Animate 게시판",
            "Audition 게시판",
            "Bridge 게시판",
            "Character Animator 게시판",
            "Creative Cloud 게시판",
            "Illustrator on the web (베타)",
            "Media Encoder 게시판",
            "Photoshop 게시판",
            "Premiere Pro 게시판",
            "Premiere Rush 게시판",
            "Stock Contributor 게시판",
            "Stock 게시판",
            "계정, 결제 및 플랜",
            "다운로드 및 설치 게시판"
        ],
        "일러스트레이션": [
            "Creative Cloud 게시판",
            "Fresco 게시판",
            "Illustrator 게시판",
            "Photoshop 게시판",
            "Stock Contributor 게시판",
            "계정, 결제 및 플랜",
            "다운로드 및 설치 게시판"
        ],
        "UI 및 UX": [
            "Adobe Fonts 게시판",
            "Adobe XD 게시판",
            "After Effects 게시판",
            "Animate 게시판",
            "Creative Cloud 게시판",
            "Illustrator on the web (베타)",
            "Illustrator 게시판",
            "Photoshop 게시판",
            "계정, 결제 및 플랜",
            "다운로드 및 설치 게시판"
        ],
        "Acrobat 및 PDF": [
            "Acrobat Reader 게시판",
            "Acrobat 게시판",
            "Adobe Fonts 게시판",
            "Creative Cloud 게시판",
            "Illustrator on the web (베타)",
            "InDesign 게시판",
            "Stock 게시판",
            "계정, 결제 및 플랜",
            "글꼴 및 타이포그래피",
            "다운로드 및 설치 게시판"
        ],
        "비즈니스 솔루션": [
            "Stock Contributor 게시판",
            "커뮤니티 사용 게시판"
        ],
        "3D 및 AR": [
            "Dimension 게시판",
            "Mixamo 게시판",
            "Substance 3D Assets 및 커뮤니티 에셋 게시판",
            "Substance 3D Designer 게시판",
            "Substance 3D Painter 게시판",
            "Substance 3D Sampler 게시판",
            "Substance 3D Stager 게시판",
            "Substance 3D 플러그인 게시판"
        ]
    }
};